import {
  Activity,
  Apple,
  Baby,
  Biohazard,
  Bone,
  BookHeart,
  BookOpenCheck,
  Brain,
  BriefcaseMedical,
  Dna,
  Droplet,
  Dumbbell,
  Ear,
  Eye,
  FlaskConical,
  Gavel,
  Hand,
  HandHeart,
  HeartPulse,
  Hospital,
  Microscope,
  MoveRight,
  Pill,
  PlusCircle,
  Radiation,
  ScanLine,
  Scissors,
  ShieldCheck,
  Skull,
  Stethoscope,
  Syringe,
  TestTube,
  Thermometer,
  User,
  Users,
  Venus,
} from "lucide-react";

import { MedicalSpecialty } from "@/app/(protected)/doctors/_constants";

export const medicalSpecialtiesWithIcons = [
  {
    value: MedicalSpecialty.ALERGOLOGIA,
    label: "Alergologia",
    icon: Biohazard,
  },
  {
    value: MedicalSpecialty.ANESTESIOLOGIA,
    label: "Anestesiologia",
    icon: Syringe,
  },
  { value: MedicalSpecialty.ANGIOLOGIA, label: "Angiologia", icon: MoveRight },
  {
    value: MedicalSpecialty.CANCEROLOGIA,
    label: "Cancerologia",
    icon: Radiation,
  },
  {
    value: MedicalSpecialty.CARDIOLOGIA,
    label: "Cardiologia",
    icon: HeartPulse,
  },
  {
    value: MedicalSpecialty.CIRURGIA_CARDIOVASCULAR,
    label: "Cirurgia Cardiovascular",
    icon: Activity,
  },
  {
    value: MedicalSpecialty.CIRURGIA_CABECA_PESCOCO,
    label: "Cirurgia de Cabeça e Pescoço",
    icon: Skull,
  },
  {
    value: MedicalSpecialty.CIRURGIA_DIGESTIVA,
    label: "Cirurgia do Aparelho Digestivo",
    icon: ScanLine,
  },
  {
    value: MedicalSpecialty.CIRURGIA_GERAL,
    label: "Cirurgia Geral",
    icon: Hospital,
  },
  {
    value: MedicalSpecialty.CIRURGIA_PEDIATRICA,
    label: "Cirurgia Pediátrica",
    icon: Baby,
  },
  {
    value: MedicalSpecialty.CIRURGIA_PLASTICA,
    label: "Cirurgia Plástica",
    icon: Scissors,
  },
  {
    value: MedicalSpecialty.CIRURGIA_TORACICA,
    label: "Cirurgia Torácica",
    icon: BookHeart,
  },
  {
    value: MedicalSpecialty.CIRURGIA_VASCULAR,
    label: "Cirurgia Vascular",
    icon: Activity,
  },
  {
    value: MedicalSpecialty.CLINICA_MEDICA,
    label: "Clínica Médica",
    icon: Stethoscope,
  },
  { value: MedicalSpecialty.DERMATOLOGIA, label: "Dermatologia", icon: Hand },
  {
    value: MedicalSpecialty.ENDOCRINOLOGIA,
    label: "Endocrinologia e Metabologia",
    icon: FlaskConical,
  },
  { value: MedicalSpecialty.ENDOSCOPIA, label: "Endoscopia", icon: Microscope },
  {
    value: MedicalSpecialty.GASTROENTEROLOGIA,
    label: "Gastroenterologia",
    icon: TestTube,
  },
  { value: MedicalSpecialty.GERIATRIA, label: "Geriatria", icon: User },
  {
    value: MedicalSpecialty.GINECOLOGIA_OBSTETRICIA,
    label: "Ginecologia e Obstetrícia",
    icon: Venus,
  },
  {
    value: MedicalSpecialty.HEMATOLOGIA,
    label: "Hematologia e Hemoterapia",
    icon: Droplet,
  },
  { value: MedicalSpecialty.HEPATOLOGIA, label: "Hepatologia", icon: Pill },
  { value: MedicalSpecialty.HOMEOPATIA, label: "Homeopatia", icon: Dna },
  { value: MedicalSpecialty.INFECTOLOGIA, label: "Infectologia", icon: Skull },
  { value: MedicalSpecialty.MASTOLOGIA, label: "Mastologia", icon: HandHeart },
  {
    value: MedicalSpecialty.MEDICINA_DE_EMERGENCIA,
    label: "Medicina de Emergência",
    icon: PlusCircle,
  },
  {
    value: MedicalSpecialty.MEDICINA_DO_ESPORTO,
    label: "Medicina do Esporte",
    icon: Dumbbell,
  },
  {
    value: MedicalSpecialty.MEDICINA_DO_TRABALHO,
    label: "Medicina do Trabalho",
    icon: BriefcaseMedical,
  },
  {
    value: MedicalSpecialty.MEDICINA_DE_FAMILIA,
    label: "Medicina de Família e Comunidade",
    icon: Users,
  },
  {
    value: MedicalSpecialty.MEDICINA_FISICA_REABILITACAO,
    label: "Medicina Física e Reabilitação",
    icon: Dumbbell,
  },
  {
    value: MedicalSpecialty.MEDICINA_INTENSIVA,
    label: "Medicina Intensiva",
    icon: ShieldCheck,
  },
  {
    value: MedicalSpecialty.MEDICINA_LEGAL,
    label: "Medicina Legal e Perícia Médica",
    icon: Gavel,
  },
  { value: MedicalSpecialty.NEFROLOGIA, label: "Nefrologia", icon: Droplet },
  {
    value: MedicalSpecialty.NEUROCIRURGIA,
    label: "Neurocirurgia",
    icon: Brain,
  },
  { value: MedicalSpecialty.NEUROLOGIA, label: "Neurologia", icon: Brain },
  { value: MedicalSpecialty.NUTROLOGIA, label: "Nutrologia", icon: Apple },
  { value: MedicalSpecialty.OFTALMOLOGIA, label: "Oftalmologia", icon: Eye },
  {
    value: MedicalSpecialty.ONCOLOGIA_CLINICA,
    label: "Oncologia Clínica",
    icon: Radiation,
  },
  {
    value: MedicalSpecialty.ORTOPEDIA_TRAUMATOLOGIA,
    label: "Ortopedia e Traumatologia",
    icon: Bone,
  },
  {
    value: MedicalSpecialty.OTORRINOLARINGOLOGIA,
    label: "Otorrinolaringologia",
    icon: Ear,
  },
  { value: MedicalSpecialty.PATOLOGIA, label: "Patologia", icon: Microscope },
  {
    value: MedicalSpecialty.PATOLOGIA_CLINICA,
    label: "Patologia Clínica/Medicina Laboratorial",
    icon: Microscope,
  },
  { value: MedicalSpecialty.PEDIATRIA, label: "Pediatria", icon: Baby },
  {
    value: MedicalSpecialty.PNEUMOLOGIA,
    label: "Pneumologia",
    icon: BookHeart,
  },
  {
    value: MedicalSpecialty.PSIQUIATRIA,
    label: "Psiquiatria",
    icon: BookOpenCheck,
  },
  {
    value: MedicalSpecialty.RADIOLOGIA,
    label: "Radiologia e Diagnóstico por Imagem",
    icon: ScanLine,
  },
  {
    value: MedicalSpecialty.RADIOTERAPIA,
    label: "Radioterapia",
    icon: Radiation,
  },
  {
    value: MedicalSpecialty.REUMATOLOGIA,
    label: "Reumatologia",
    icon: HandHeart,
  },
  { value: MedicalSpecialty.UROLOGIA, label: "Urologia", icon: Thermometer },
];
