import "./globals.css";

import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import { NuqsAdapter } from "nuqs/adapters/next/app";

import { Toaster } from "@/components/ui/sonner";
import ReactQueryProvider from "@/providers/react-query";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${manrope.variable} antialiased`}
        style={{
          minHeight: "100vh",
          minWidth: "100vw",
          maxWidth: "100vw",
          maxHeight: "100vh",
          overflowX: "hidden",
        }}
      >
        <div
          style={{
            maxWidth: "1550px",
            margin: "0 auto",
            width: "100%",
            minHeight: "100vh",
          }}
        >
          <ReactQueryProvider>
            <NuqsAdapter>{children}</NuqsAdapter>
          </ReactQueryProvider>
        </div>
        <Toaster position="top-right" richColors theme="light" />
      </body>
    </html>
  );
}
